//
//  FeedConfigurator.swift
//  Mabius
//
//  Created by Timafei Harhun on 3/2/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

class FeedConfigurator {
    
    // MARK: - Object lifecycle

    static let instance = FeedConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: FeedViewController) {
        
        let router = FeedRouter(viewController: viewController)
        let presenter = FeedPresenter(output: viewController)
        let interactor = FeedInteractor(output: presenter)
        
        viewController.output = interactor
        viewController.router = router
    }
}
