//
//  FeedModels.swift
//  Mabius
//
//  Created by Timafei Harhun on 3/2/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

func getLogoFor(project: String) -> UIImage? {
    switch project {
    case "mabius":
        return #imageLiteral(resourceName: "logo")
    case "enactus":
        return #imageLiteral(resourceName: "imgInactus")
    default:
        return nil
    }
}

func getProjectTitle(for type: String) -> String? {
    switch type {
    case "mabius_idea":
        return "Проект"
    case "enactus_event":
        return "Мероприятие"
    case "enactus_idea":
        return "Идея"
    default:
        return nil
    }
}

import UIKit

struct Feed {
    
    struct Input {
        
        var page: Int
        var perPage: Int
        var search : String?
        var params: Filter.Input
        var currentLocation: Location?
    }

    struct Output {
        
        var page: Int
        var total: Int
        var points: [Point]
    }

    struct ViewModel {
        
        var points = [Point]()
        var loading = false
        var currentLocation: Location?
    }
    
    struct Batch {
        var page = 0
        var total = 0
    }
}
