//
//  FeedRouter.swift
//  Mabius
//
//  Created by Timafei Harhun on 3/2/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FeedRouterInput {
    func openPoint(_ id: Int)
    func openLikes(pointId: Int)
    func openComments(pointId: Int)
    func showHint() -> HintsViewController
    func hideHint()
}

class FeedRouter: FeedRouterInput {
    
    weak var viewController: FeedViewController!

    init(viewController: FeedViewController) {
        self.viewController = viewController
    }

    // MARK: - Navigation

    func openPoint(_ id: Int) {
        UIApplication.openUrl("cyl://PointViewController?pointId=\(id)")
    }
    
    func showHint() -> HintsViewController {
        let vc = viewController.storyboard?.instantiateViewController(withIdentifier: "HintsViewController") as? HintsViewController
        vc?.view.frame = UIScreen.main.bounds
        viewController.tabBarController?.addChildViewController(vc!)
        viewController.tabBarController?.view.addSubview((vc?.view)!)
        
        return vc!
    }
    
    func hideHint() {
        viewController.tabBarController?.view.subviews.last?.removeFromSuperview()
        viewController.tabBarController?.childViewControllers.last?.removeFromParentViewController()
    }
    
    func openLikes(pointId: Int) {
        UIApplication.openUrl("cyl://WhoViewController?pointId=\(pointId)")
    }
    
    func openComments(pointId: Int) {
        UIApplication.openUrl("cyl://PointViewController?pointId=\(pointId)&scrollToComments=true")
    }
    
    func openFilter() {
        viewController.sideViewController()?.filterController().type = .feed
        viewController.sideViewController()?.filterController().delegate = viewController
        viewController.sideViewController()?.toogleRightViewController()
    }
}
