//
//  ChangeMailInteractor.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/21/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol ChangeMailInteractorInput {
    
    func checkInput(_ input: ChangeMail.Input)
    func change(with input: ChangeMail.Input)
}

class ChangeMailInteractor: ChangeMailInteractorInput, ChangeMailWorkerOutput {
    
    private let output: ChangeMailPresenterInput
    private let worker: ChangeMailWorker

    init(output: ChangeMailPresenterInput) {
        self.output = output
        worker = ChangeMailWorker()
        worker.output = self
    }

    // MARK: - Business logic

    func checkInput(_ input: ChangeMail.Input) {
        output.handleInput(input.isValid)
    }
    
    func change(with input: ChangeMail.Input) {
        output.beginChange()
        worker.change(with: input)
    }

    // MARK: - Worker Output
    
    func didChanged(with output: ChangeMail.Output) {
        self.output.didChanged()
    }
    
    func gotError(_ error: Error) {
        output.gotError(error)
    }
}
