//
//  ChangeMailWorker.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/21/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol ChangeMailWorkerInput {
    func change(with input: ChangeMail.Input)
}

protocol ChangeMailWorkerOutput: class {
    func didChanged(with output: ChangeMail.Output)
    func gotError(_ error: Error)
}

class ChangeMailWorker: ChangeMailWorkerInput {
    
    weak var output: ChangeMailWorkerOutput?

    // MARK: - Business Logic
    
    func change(with input: ChangeMail.Input) {
        
        let params = ChangeEmailParams()
        params.email = input.email
        params.password = input.password
        
        _ = ChangeEmail(params: params).exec { result in
            switch result {
            case .value(_):
                self.output?.didChanged(with: ChangeMail.Output())
            case .error(let error):
                self.output?.gotError(error)
            }
        }
    }
}
