//
//  ChangeMailViewController.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/21/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import SwiftyUserDefaults

class ChangeMailViewController: BaseViewController, ChangeMailPresenterOutput {
    
    @IBOutlet weak var emailTextField: TextField!
    @IBOutlet weak var passTextField: TextField!
    @IBOutlet weak var button: UIButton!
    
    var output: ChangeMailInteractorInput!
    var router: ChangeMailRouter!
    
    var input: ChangeMail.Input {
        return ChangeMail.Input(email: emailTextField.text, password: passTextField.text)
    }

    // MARK: - Object lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()
        
        ChangeMailConfigurator.instance.configure(viewController: self)
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        
        emailTextField.becomeFirstResponder()
        
        emailTextField.addTarget(self, action: #selector(inputChanged(_:)), for: .editingChanged)
        passTextField.addTarget(self, action: #selector(inputChanged(_:)), for: .editingChanged)
        
        output.checkInput(input)
    }

    // MARK: - Event handling

    @IBAction func confirm() {
        output.change(with: input)
    }
    
    @objc func inputChanged(_ textField: UITextField) {
        output.checkInput(input)
    }

    // MARK: - Display logic
    
    func didChanged() {
        if let user = User(JSON: Defaults[.userJSON]) {
            user.email = emailTextField.text
            Defaults[.userJSON] = user.toJSON()
        }
        router.proceedBack()
    }

    func showError(_ error: String) {
        alert("Errors.error".localize(), message: error, cancel: "OK")
    }
    
    func toggleButton(_ isEnabled: Bool) {
        button.isEnabled = isEnabled
    }
    
    func toggleView(_ isEnabled: Bool) {
        view.isUserInteractionEnabled = isEnabled
    }
}
