//
//  ChangeMailConfigurator.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/21/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

class ChangeMailConfigurator {
    
    // MARK: - Object lifecycle

    static let instance = ChangeMailConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: ChangeMailViewController) {
        
        let router = ChangeMailRouter(viewController: viewController)
        let presenter = ChangeMailPresenter(output: viewController)
        let interactor = ChangeMailInteractor(output: presenter)
        
        viewController.output = interactor
        viewController.router = router
    }
}
