//
//  FilterModels.swift
//  Mabius
//
//  Created by Work on 3/3/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

enum FilterType: Int {
    case feed = 0
    case map
}

enum SortType: String {
    case new      = "new"
    case distance = "distance"
    case likes    = "likes"
}

struct Filter {
    
    struct Input {
        var sort : String?
        var categories = [Int]()
    }

    struct Output {}

    struct ViewModel {
        var categories: [String: Int]
        
        init() {
            categories = [:]
        }
    }
}

extension SortType {
    func localizable() -> String { return NSLocalizedString(self.rawValue, comment: "") }
}
