//
//  FilterWorker.swift
//  Mabius
//
//  Created by Work on 3/3/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol FilterWorkerInput {
    func loadProjects()
}

protocol FilterWorkerOutput: class {
    
    func didLoadProjects()
    func gotError(_ error: Error)
}

class FilterWorker: FilterWorkerInput {
    
    weak var output: FilterWorkerOutput?

    // MARK: - Business Logic

    func loadProjects() {
        ProjectsProvider.instance.load { (success) in
            if success {
                self.output?.didLoadProjects()
            } else {
                self.output?.gotError(NetworkError.badResponse)
            }
        }
    }
}
