//
//  FilterInteractor.swift
//  Mabius
//
//  Created by Work on 3/3/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol FilterInteractorInput {
    func loadProjects()
}

class FilterInteractor: FilterInteractorInput, FilterWorkerOutput {
    
    private let output: FilterPresenterInput
    private let worker: FilterWorker

    init(output: FilterPresenterInput) {
        self.output = output
        worker = FilterWorker()
        worker.output = self
    }

    // MARK: - Business logic

    func loadProjects() {
        output.beganLoadProjects()
        worker.loadProjects()
    }

    // MARK: - Worker Output
    
    func didLoadProjects() {
        output.didLoadProjects()
    }
    
    func gotError(_ error: Error) {
        output.gotError(error)
    }
}
