//
//  FilterPresenter.swift
//  Mabius
//
//  Created by Work on 3/3/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol FilterPresenterInput {
    
    func beganLoadProjects()
    func didLoadProjects()
    func gotError(_ error: Error)
}

protocol FilterPresenterOutput: class {
    
    func didLoadProjects()
    func showError(_ error: String)
    func toggleView(_ isEnabled: Bool)
}

class FilterPresenter: FilterPresenterInput {
    
    private weak var output: FilterPresenterOutput?

    init(output: FilterPresenterOutput){
        self.output = output
    }

    // MARK: - Presentation logic

    func beganLoadProjects() {
        output?.toggleView(false)
    }
    
    func didLoadProjects() {
        output?.toggleView(true)
        output?.didLoadProjects()
    }
    
    func gotError(_ error: Error) {
        output?.toggleView(true)
        output?.showError(String(describing: error))
    }
}
