//
//  PointModels.swift
//  Mabius
//
//  Created by Timafei Harhun on 10/03/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

struct PointDetails {
    
    struct Input {
        
        struct Comment {
            var pointId: Int
            var comment: String
        }
        
        struct PointId {
            var pointId: Int
        }
        
        struct CommentsList {
            var pointId: Int
            var page: Int
            var perPage: Int
        }
    }

    struct Output {
        
        struct UserPoint {
            var user: User
            var point: Point
        }
        
        struct Comments {
            var page: Int
            var total: Int
            var comments: [UserComment]
        }
    }

    struct ViewModel {
        var pointId = 0
    
        var point = Point()
        var owner = User()
        var comments = [UserComment]()
        
        var scrollToComments = false
        var loading = true
    }
    
    struct UserComment {
        var user: User
        var comment: Comment
    }
    
    struct Batch {
        var page = 0
        var total = 0
    }
}

let commentsPerPage = 5
