//
//  PointConfigurator.swift
//  Mabius
//
//  Created by Timafei Harhun on 10/03/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

class PointConfigurator {
    
    // MARK: - Object lifecycle

    static let instance = PointConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: PointViewController) {
        
        let router = PointRouter(viewController: viewController)
        let presenter = PointPresenter(output: viewController)
        let interactor = PointInteractor(output: presenter)
        
        viewController.output = interactor
        viewController.router = router
    }
}
