//
//  PointRouter.swift
//  Mabius
//
//  Created by Timafei Harhun on 10/03/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PointRouterInput {
    func share(with model: PointDetails.ViewModel)
    func editPoint(with model: PointDetails.ViewModel)
    func openUser(_ id: Int)
    func openLikes(for pointId: Int)
}

class PointRouter: PointRouterInput {
    
    weak var viewController: PointViewController!

    init(viewController: PointViewController) {
        self.viewController = viewController
    }

    // MARK: - Navigation

    func share(with model: PointDetails.ViewModel) {
        let vc = UIActivityViewController(activityItems: [model.point.title ?? "pointTitle", model.point.shareUrl ?? "url"], applicationActivities: nil)
        viewController.present(vc, animated: true, completion: nil)
    }
    
    func editPoint(with model: PointDetails.ViewModel) {
        let vc = viewController.storyboard?.instantiateViewController(withIdentifier: "Step2ViewController") as! Step2ViewController
        vc.transfer = Step2.Transfer(step1: Step1.Input(selectedProject: ProjectKind.getProjectKind(by: model.point.project!), selectedType: ProjectType.getProjectType(by: model.point.type!)))
        viewController.navigationController?.pushViewController(vc, animated: true)
        vc.point = model.point
    }
    
    func openUser(_ id: Int) {
        if User.fromDefaults?.id == id {
            UIApplication.openUrl("cyl://ProfileViewController?userId=\(id)&selfProfile=true&fromPoint=true")
        } else {
            UIApplication.openUrl("cyl://ProfileViewController?userId=\(id)&selfProfile=false&fromPoint=true")
        }
    }
    
    func openLikes(for pointId: Int) {
        UIApplication.openUrl("cyl://WhoViewController?pointId=\(pointId)")
    }
}
