//
//  FilterConfigurator.swift
//  Mabius
//
//  Created by Work on 3/3/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

class FilterConfigurator {
    
    // MARK: - Object lifecycle

    static let instance = FilterConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: FilterViewController) {

        let presenter = FilterPresenter(output: viewController)
        let interactor = FilterInteractor(output: presenter)
        
        viewController.output = interactor
    }
}
