//
//  FilterPresenter.swift
//  Mabius
//
//  Created by Work on 3/3/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol FilterPresenterInput {
    func beganLoading()
    func endLoading()
    func didLoad(data: Filter.Output)
    func gotError(_ error: Error)
}

protocol FilterPresenterOutput: class {
    func didLoad(data: Filter.Output)
    func showError(_ error: String)
    func toggleView(_ isEnabled: Bool)
}

class FilterPresenter: FilterPresenterInput {
    
    private weak var output: FilterPresenterOutput!

    init(output: FilterPresenterOutput){
        self.output = output
    }

    // MARK: - Presentation logic

    func beganLoading() {
        output.toggleView(false)
    }
    
    func endLoading() {
        output.toggleView(true)
    }
    
    func didLoad(data: Filter.Output) {
        output.didLoad(data: data)
    }
    
    func gotError(_ error: Error) {
        output.showError(String(describing: error))
    }
}
