//
//  PlacePresenter.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/27/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol PlacePresenterInput {
    func beginLoad()
    func didLoadLocation(_ response: Place.Output)
    func gotError(_ error: Error)
}

protocol PlacePresenterOutput: class {
    func toggleView(_ isEnabled: Bool)
    func didLoadLocation(_ response: Place.Output)
    func showError(_ error: String)
}

class PlacePresenter: PlacePresenterInput {
    
    private weak var output: PlacePresenterOutput?

    init(output: PlacePresenterOutput) {
        self.output = output
    }

    // MARK: - Presentation logic

    func beginLoad() {
        beginActivity()
    }
    
    func didLoadLocation(_ response: Place.Output) {
        endActivity()
        output?.didLoadLocation(response)
    }
    
    func gotError(_ error: Error) {
        endActivity()
        output?.showError(String(describing: error))
    }
    
    // MARK: - Activity
    
    fileprivate func beginActivity() {
        output?.toggleView(false)
    }
    
    fileprivate func endActivity() {
        output?.toggleView(true)
    }
}
