//
//  PlaceConfigurator.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/27/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

class PlaceConfigurator {
    
    // MARK: - Object lifecycle

    static let instance = PlaceConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: PlaceViewController) {
        
        let router = PlaceRouter(viewController: viewController)
        let presenter = PlacePresenter(output: viewController)
        let interactor = PlaceInteractor(output: presenter)
        
        viewController.output = interactor
        viewController.router = router
    }
}
