//
//  NotificationsModels.swift
//  Mabius
//
//  Created by Timafei Harhun on 3/13/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

let notificationsPerPage = 7

struct Notifications {
    
    struct Input {
        var page: Int
        var perPage: Int
    }

    struct Output {
        var page: Int
        var total: Int
        var notifications: [NotificationPoint]
    }

    struct ViewModel {
        var notifications = [NotificationPoint]()
        var loading = false
    }
    
    struct Batch {
        var page = 1
        var total = 0
    }
    
    struct NotificationPoint {
        var notification: NotificationInfo
        var pointTitle: String
    }
}
