//
//  NotificationsPresenter.swift
//  Mabius
//
//  Created by Timafei Harhun on 3/13/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol NotificationsPresenterInput {
    
    func beginLoad()

    func didLoadNotifications(_ response: Notifications.Output)
    func didLoadMoreNotifications(_ response: Notifications.Output)
    func gotError(_ error: Error)
}

protocol NotificationsPresenterOutput: class {
    
    func didLoadNotifications(_ response: Notifications.Output)
    func didLoadMoreNotifications(_ response: Notifications.Output)
    
    func showError(_ error: String)
    func toggleView(_ isEnabled: Bool)
}

class NotificationsPresenter: NotificationsPresenterInput {
    
    private weak var output: NotificationsPresenterOutput!

    init(output: NotificationsPresenterOutput) {
        self.output = output
    }

    // MARK: - Presentation logic
    
    func beginLoad() {
        beginActivity()
    }

    func didLoadNotifications(_ response: Notifications.Output) {
        endActivity()
        output.didLoadNotifications(response)
    }
    
    func didLoadMoreNotifications(_ response: Notifications.Output) {
        endActivity()
        output.didLoadMoreNotifications(response)
    }
    
    func gotError(_ error: Error) {
        endActivity()
        output.showError(String(describing: error))
    }
    
    // MARK: - Activity
    
    fileprivate func beginActivity() {
        output.toggleView(false)
    }
    
    fileprivate func endActivity() {
        output.toggleView(true)
    }
}
