//
//  NotificationsRouter.swift
//  Mabius
//
//  Created by Timafei Harhun on 3/13/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol NotificationsRouterInput {
    func openPoint(with pointId: Int)
    func openUser(with userId: Int)
}

class NotificationsRouter: NotificationsRouterInput {
    
    weak var viewController: NotificationsViewController!

    init(viewController: NotificationsViewController) {
        self.viewController = viewController
    }

    // MARK: - Navigation

    func openPoint(with pointId: Int) {
        UIApplication.openUrl("cyl://PointViewController?pointId=\(pointId)")
    }
    
    func openUser(with userId: Int) {
        UIApplication.openUrl("cyl://ProfileViewController?userId=\(userId)&selfProfile=false")
    }
}
