//
//  RestorePassConfigurator.swift
//  Mabius
//
//  Created by Work on 2/20/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

class RestorePassConfigurator {
    // MARK: - Object lifecycle

    static let instance = RestorePassConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: RestorePassViewController) {
        
        let router = RestorePassRouter(viewController: viewController)
        let presenter = RestorePassPresenter(output: viewController)
        let interactor = RestorePassInteractor(output: presenter)
        
        viewController.output = interactor
        viewController.router = router
    }
}
