//
//  RestorePassRouter.swift
//  Mabius
//
//  Created by Work on 2/20/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol RestorePassRouterInput {
    
    func proceedNext()
}

class RestorePassRouter: RestorePassRouterInput {
    
    weak var viewController: RestorePassViewController!

    init(viewController: RestorePassViewController) {
        self.viewController = viewController
    }

    // MARK: - Navigation

    func proceedNext() {
        UIApplication.openUrl("cyl://InfoViewController?type=0")
    }
}
