//
//  RestorePassModelsModels.swift
//  Mabius
//
//  Created by Work on 2/20/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

struct RestorePassModels {
    
    struct Input {
        let email: String?
    }

    struct Output {
    }

    struct ViewModel {
    }
}

extension RestorePassModels.Input {
    
    var isValid: Bool {
        if let value = email {
            return value.isEmail
        }
        return false
    }
}
