//
//  RestorePassPresenter.swift
//  Mabius
//
//  Created by Work on 2/20/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol RestorePassPresenterInput {
    
    func beginRestore() 
    func didRestore()
    func gotError(_ error: Error)
    func handleInput(_ isValid: Bool)
}

protocol RestorePassPresenterOutput: class {
    
    func didRestore()
    func showError(_ error: String)
    func toggleButton(_ isEnabled: Bool)
    func toggleView(_ isEnabled: Bool)
}

class RestorePassPresenter: RestorePassPresenterInput {
    
    private weak var output: RestorePassPresenterOutput?

    init(output: RestorePassPresenterOutput) {
        self.output = output
    }

    // MARK: - Presentation logic
    
    func beginRestore() {
        output?.toggleButton(false)
        output?.toggleView(false)
    }
    
    func didRestore() {
        output?.toggleButton(true)
        output?.toggleView(true)
        output?.didRestore()
    }
    
    func gotError(_ error: Error) {
        output?.toggleButton(true)
        output?.toggleView(true)
        output?.showError(String(describing: error))
    }
    
    func handleInput(_ isValid: Bool) {
        output?.toggleButton(isValid)
    }
    
}
