//
//  RestorePassWorker.swift
//  Mabius
//
//  Created by Work on 2/20/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol RestorePassWorkerInput {
    
    func restore(with input:RestorePassModels.Input)
}

protocol RestorePassWorkerOutput: class {
    
    func didRestore()
    func gotError(_ error: Error)
}

class RestorePassWorker: RestorePassWorkerInput {
    
    weak var output: RestorePassWorkerOutput?

    // MARK: - Business Logic

    func restore(with input:RestorePassModels.Input) {
        RecoverPassword(email: input.email).exec { result in
            switch result {
            case .value(_):
                self.output?.didRestore()
            case .error(let error):
                self.output?.gotError(error)
            }
        }
    }
}
