//
//  Step3Interactor.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/24/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol Step3InteractorInput {
    func checkInput(_ input: Step3.Input)
    func createPoint(with input: Step3.Input, and transfer: Step3.Transfer)
    func editPoint(with input: Step3.Input, and transfer: Step3.Transfer)
}

class Step3Interactor: Step3InteractorInput, Step3WorkerOutput {
    
    private let output: Step3PresenterInput
    private let worker: Step3Worker

    init(output: Step3PresenterInput) {
        self.output = output
        worker = Step3Worker()
        worker.output = self
    }

    // MARK: - Business logic

    func checkInput(_ input: Step3.Input) {
        output.handleInput(input.isValid)
    }
    
    func createPoint(with input: Step3.Input, and transfer: Step3.Transfer) {
        output.beginLoad()
        worker.createPoint(with: input, and: transfer)
    }
    
    func editPoint(with input: Step3.Input, and transfer: Step3.Transfer) {
        output.beginLoad()
        worker.editPoint(with: input, and: transfer)
    }

    // MARK: - Worker Output
    
    func didCreatedPoint() {
        output.didCreatedPoint()
    }
    
    func didEditedPoint() {
        output.didEditedPoint()
    }
    
    func gotError(_ error: Error) {
        output.gotError(error)
    }
}
