//
//  Step3Router.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/24/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import SwiftyUserDefaults

protocol Step3RouterInput {
    func proceed()
}

class Step3Router: Step3RouterInput {
    weak var viewController: Step3ViewController!

    init(viewController: Step3ViewController) {
        self.viewController = viewController
    }

    // MARK: - Navigation

    func proceed() {
        if viewController.point != nil {
            _ = viewController.navigationController?.popToViewController((viewController.navigationController?.viewController(PointViewController.self))!, animated: false)
        } else {
            viewController.tabBarController?.selectedIndex = 0
            _ = viewController.navigationController?.popToRootViewController(animated: false)
            if let feedVC = viewController.navigationController?.topViewController as? FeedViewController { feedVC.point = viewController.point }
        }
    }
}

