//
//  Step3Presenter.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/24/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol Step3PresenterInput {
    func beginLoad()
    func handleInput(_ isValid: Bool)
    func didCreatedPoint()
    func didEditedPoint()
    func gotError(_ error: Error)
}

protocol Step3PresenterOutput: class {
    func didCreatedPoint()
    func didEditedPoint()
    func toggleButton(_ isEnabled: Bool)
    func toggleView(_ isEnabled: Bool)
    func showError(_ error: String)
}

class Step3Presenter: Step3PresenterInput {
    
    private weak var output: Step3PresenterOutput?

    init(output: Step3PresenterOutput) {
        self.output = output
    }

    // MARK: - Presentation logic
    
    func beginLoad() {
        beginActivity()
    }

    func handleInput(_ isValid: Bool) {
        output?.toggleButton(isValid)
    }
    
    func gotError(_ error: Error) {
        endActivity()
        output?.showError(String(describing: error))
    }
    
    func didCreatedPoint() {
        endActivity()
        output?.didCreatedPoint()
    }
    
    func didEditedPoint() {
        endActivity()
        output?.didEditedPoint()
    }
    
    // MARK: - Activity
    
    fileprivate func beginActivity() {
        output?.toggleButton(false)
        output?.toggleView(false)
    }
    
    fileprivate func endActivity() {
        output?.toggleButton(true)
        output?.toggleView(true)
    }
}
