//
//  LoginRouter.swift
//  Mabius
//
//  Created by Andrey Toropchin on 14.02.17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol LoginRouterInput
{
    func showRecovery()
    func proceedNext()
}

class LoginRouter: LoginRouterInput
{
    weak var viewController: LoginViewController!

    init(viewController: LoginViewController)
    {
        self.viewController = viewController
    }

    // MARK: - Navigation

    func showRecovery()
    {
        UIApplication.openUrl("cyl://RestorePassViewController")
    }

    func proceedNext()
    {
        UIApplication.openUrl("cyl://ContainerViewController")
    }
}
