//
//  LoginModels.swift
//  Mabius
//
//  Created by Andrey Toropchin on 14.02.17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

struct Login
{
    struct Input
    {
        struct ViaEmail
        {
            var login: String?
            var password: String?
        }
        struct ViaSocial
        {
            var type: String
            var token: String
        }
    }

    struct Output
    {
        var token: String
        var userId: Int
        var email: String?
    }
    
    struct ViewModel
    {
    }
}

extension Login.Input.ViaEmail
{
    var isValid: Bool {
        guard let email = login else { return false }
        guard let password = password else { return false }
        return email.isEmail && password.length >= minPasswordLength
    }
}

let minPasswordLength = 1
