//
//  LoginViewController.swift
//  Mabius
//
//  Created by Andrey Toropchin on 14.02.17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class LoginViewController: BaseViewController, LoginPresenterOutput
{
    @IBOutlet weak var emailTextField: TextField!
    @IBOutlet weak var passTextField: TextField!
    @IBOutlet weak var loginButton: UIButton!

    var output: LoginInteractorInput!
    var router: LoginRouter!

    var input: Login.Input.ViaEmail {
        return Login.Input.ViaEmail(login: emailTextField.text, password: passTextField.text)
    }

    // MARK: - Object lifecycle

    override func awakeFromNib()
    {
        super.awakeFromNib()
        LoginConfigurator.instance.configure(viewController: self)
    }

    // MARK: - View lifecycle

    override func viewDidLoad()
    {
        super.viewDidLoad()
        emailTextField.becomeFirstResponder()
        emailTextField.addTarget(self, action: #selector(inputChanged), for: .editingChanged)
        passTextField.addTarget(self, action: #selector(inputChanged), for: .editingChanged)
        inputChanged()
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)

        toggleView(true)
    }

    // MARK: - Event handling

    @IBAction func login() {
        output.login(with: input)
    }

    @IBAction func loginFb() {
        output.loginViaFb()
    }

    @IBAction func loginVk() {
        output.loginViaVk()
    }

    @IBAction func recover() {
        router.showRecovery()
    }

    @objc func inputChanged() {
        output.checkInput(input)
    }

    // MARK: - Display logic

    func didLogin() {
        router.proceedNext()
    }

    func showError(_ error: String) {
        alert("Errors.error".localize(), message: error, cancel: "OK")
    }

    func toggleButton(_ isEnabled: Bool) {
        loginButton.isEnabled = isEnabled
    }

    func toggleView(_ isEnabled: Bool) {
        view.isUserInteractionEnabled = isEnabled
    }
}
