//
//  MapConfigurator.swift
//  Mabius
//
//  Created by Timafei Harhun on 07/03/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

class MapConfigurator {
    
    // MARK: - Object lifecycle

    static let instance = MapConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: MapViewController) {
        
        let router = MapRouter(viewController: viewController)
        let presenter = MapPresenter(output: viewController)
        let interactor = MapInteractor(output: presenter)
        
        viewController.output = interactor
        viewController.router = router
    }
}
