//
//  MapModels.swift
//  Mabius
//
//  Created by Timafei Harhun on 07/03/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//
import MapKit

struct MapModels {
    
    struct Input {
        var region: MKCoordinateRegion
        var params: Filter.Input
    }

    struct Output {
        var clusters : Array<MapCluster>?
        var region : Region?
    }

    struct ViewModel {
        var point = Point()
        var shouldHideAnnotation = true
        var shouldScrollMapToUserLocation = true
    }
}
