//
//  MapRouter.swift
//  Mabius
//
//  Created by Timafei Harhun on 07/03/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MapRouterInput {
    func openPoint(_ pointId: Int)
    func openFilter()
    func openFeed()
}

class MapRouter: MapRouterInput {
    
    weak var viewController: MapViewController!

    init(viewController: MapViewController) {
        self.viewController = viewController
    }

    // MARK: - Navigation

    func openFilter() {
        viewController.sideViewController()?.filterController().type = .map
        viewController.sideViewController()?.filterController().delegate = viewController
        viewController.sideViewController()?.toogleRightViewController()
    }
    
    func openFeed() {
        _ = viewController.navigationController?.popViewController(animated: false)
    }
    
    func openPoint(_ pointId: Int) {
        UIApplication.openUrl("cyl://PointViewController?pointId=\(pointId)&scrollToComments=false")
    }
    
    func openLikes(pointId: Int) {
        UIApplication.openUrl("cyl://WhoViewController?pointId=\(pointId)")
    }
    
    func openComments(pointId: Int) {
        UIApplication.openUrl("cyl://PointViewController?pointId=\(pointId)&scrollToComments=true")
    }
}
