//
//  RegisterModels.swift
//  Mabius
//
//  Created by Timafei Harhun on 16.02.17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

struct Register {
    
    struct Input {
        struct Data {
            var email: String?
            var password: String?
            var repeatPassword: String?
            var firstName: String?
            var secondName: String?
            var gender: Gender?
            var invite: String?
            var socialTokens = [SocialToken]()
        }
    }

    struct Output {
        var token : String! // Auth token
        var user : Int! // Id newly added user
        var email : String?
        var password: String?
    }

    struct ViewModel {
    }
}

extension Register.Input.Data {
    
    var isValid: Bool {
        guard let email = email else { return false }
        guard let password = password else { return false }
        guard let repeatPassword = repeatPassword else { return false }
        guard let firstName = firstName else { return false }
        guard let secondName = secondName else { return false }
        guard gender != nil else { return false }
        guard let invite = invite else { return false }
        return email.isEmail &&
                password.length >= minPasswordLength && repeatPassword.length >= minPasswordLength && password == repeatPassword &&
                firstName.length > minNamesLength && secondName.length > minNamesLength &&
                invite.length > minInviteLength
    }
}

let minNamesLength = 1
let minInviteLength = -1
