//
//  RegisterRouter.swift
//  Mabius
//
//  Created by Timafei Harhun on 16.02.17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import SafariServices

protocol RegisterRouterInput {
    
    func proceedBack()
    func proceedNext()
    
    func showTermsAndConditions()
}

class RegisterRouter: RegisterRouterInput {
    
    weak var viewController: RegisterViewController!

    init(viewController: RegisterViewController) {
        self.viewController = viewController
    }

    // MARK: - Navigation

    func proceedBack() {
        UIApplication.openUrl("cyl://root")
    }
    
    func proceedNext() {
        UIApplication.openUrl("cyl://ContainerViewController")
    }
    
    func showTermsAndConditions() {
        let urlString = "http://files.meallions.show/user_agreement_application_meallions.pdf"
        
        if let url = URL(string: urlString) {
            let svc = SFSafariViewController(url: url, entersReaderIfAvailable: true)
            viewController.present(svc, animated: true)
        }
    }
}
