//
//  RegisterPresenter.swift
//  Mabius
//
//  Created by Timafei Harhun on 16.02.17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol RegisterPresenterInput {
    
    func beganRegister()
    func didRegister()
    func beganCheckInvite()
    func didCheckInvite(_ isValid: Bool)
    func didAddSocial(_ type: SocialType, profile: SocialProfile)
    func gotError(_ error: Error)
    func handleInput(_ isValid: Bool)
    func handleInvite(_ isValid: Bool)
}

protocol RegisterPresenterOutput: class {
    
    func didRegister()
    func didCheckInvite(_ isValid: Bool)
    func didAddSocial(_ type: SocialType, profile: SocialProfile)
    func showError(_ error: String)
    func toggleButton(_ isEnabled: Bool)
    func toggleView(_ isEnabled: Bool)
    func toggleScreen()
}

class RegisterPresenter: RegisterPresenterInput {
    
    private weak var output: RegisterPresenterOutput?

    init(output: RegisterPresenterOutput) {
        
        self.output = output
    }

    func beganRegister() {
        beganActivity()
    }
    
    func didRegister() {
        endActivity()
        output?.didRegister()
    }
    
    func beganCheckInvite() {
        beganActivity()
    }
    
    func didCheckInvite(_ isValid: Bool) {
        endActivity()
        output?.didCheckInvite(isValid)
    }
    
    func beganAddSocial() {
        beganActivity()
    }
    
    func didAddSocial(_ type: SocialType, profile: SocialProfile) {
        endActivity()
        output?.didAddSocial(type, profile: profile)
    }
    
    func beganActivity() {
        output?.toggleButton(false)
        output?.toggleView(false)
    }
    
    func endActivity() {
        output?.toggleButton(true)
        output?.toggleView(true)
    }
    
    func gotError(_ error: Error) {
        output?.toggleButton(true)
        output?.toggleView(true)
        output?.showError(String(describing: error))
    }
    
    func handleInput(_ isValid: Bool) {
        output?.toggleButton(isValid)
    }
    
    func handleInvite(_ isValid: Bool) {
        if !isValid {
            output?.toggleScreen()
        }
    }
}
