//
//  RegisterConfigurator.swift
//  Mabius
//
//  Created by Timafei Harhun on 16.02.17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

class RegisterConfigurator {
    // MARK: - Object lifecycle

    static let instance = RegisterConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: RegisterViewController) {
        
        let router = RegisterRouter(viewController: viewController)
        let presenter = RegisterPresenter(output: viewController)
        let interactor = RegisterInteractor(output: presenter)
        
        viewController.output = interactor
        viewController.router = router
    }
}
