//
//  ProfileInteractor.swift
//  Mabius
//
//  Created by Timafei Harhun on 14/03/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol ProfileInteractorInput {
    
    func loadCreatedPoints(for userId: Int)
    func loadLikedPoints(for userId: Int)
    
    func like(for point: Point)
    func removeLike(for point: Point)
    
    func getUser(by userId: Int)
}

class ProfileInteractor: ProfileInteractorInput, ProfileWorkerOutput {
    
    private let output: ProfilePresenterInput
    private let worker: ProfileWorker

    init(output: ProfilePresenterInput) {
        self.output = output
        worker = ProfileWorker()
        worker.output = self
    }

    // MARK: - Business logic
    
    func loadCreatedPoints(for userId: Int) {
        output.beginLoad()
        worker.loadCreatedPoints(for: userId)
    }
    
    func loadLikedPoints(for userId: Int) {
        output.beginLoad()
        worker.loadLikedPoints(for: userId)
    }
    
    func like(for point: Point) {
        output.beginLoad()
        worker.like(for: point)
    }
    
    func removeLike(for point: Point) {
        output.beginLoad()
        worker.removeLike(for: point)
    }
    
    func getUser(by userId: Int) {
        output.beginLoad()
        worker.getUser(by: userId)
    }

    // MARK: - Worker Output
    
    func didLoadCreatedPoints(_ response: Profile.Output) {
        output.didLoadCreatedPoints(response)
    }
    
    func didLoadLikedPoints(_ response: Profile.Output) {
        output.didLoadLikedPoints(response)
    }
    
    func didLike(for point: Point) {
        output.didLike(for: point)
    }
    
    func didRemoveLike(for point: Point) {
        output.didRemoveLike(for: point)
    }
    
    func didLoadUser(_ user: User) {
        output.didLoadUser(user)
    }
    
    func gotError(_ error: Error) {
        output.gotError(error)
    }
}
