//
//  ProfileModels.swift
//  Mabius
//
//  Created by Timafei Harhun on 14/03/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

struct Profile {
    
    struct Input {}

    struct Output {
        var points = [Point]()
    }
    
    struct ViewModel {
        var user = User()
        var createdPoints = [Point]()
        var favouritePoints = [Point]()
        
        var selfProfile = true
        var userId = Int()
        var isFromPoint = false
    }
}
