//
//  ProfileRouter.swift
//  Mabius
//
//  Created by Timafei Harhun on 14/03/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ProfileRouterInput {
    func openPointDescription(pointId: Int)
    func openLikes(pointId: Int)
    func openComments(pointId: Int)
}

class ProfileRouter: ProfileRouterInput {
    
    weak var viewController: ProfileViewController!

    init(viewController: ProfileViewController) {
        self.viewController = viewController
    }

    // MARK: - Navigation

    func openPointDescription(pointId: Int) {
        UIApplication.openUrl("cyl://PointViewController?pointId=\(pointId)")
    }
    
    func openLikes(pointId: Int) {
        UIApplication.openUrl("cyl://WhoViewController?pointId=\(pointId)")
    }
    
    func openComments(pointId: Int) {
        UIApplication.openUrl("cyl://PointViewController?pointId=\(pointId)&scrollToComments=true")
    }
}
