//
//  ProfileConfigurator.swift
//  Mabius
//
//  Created by Timafei Harhun on 14/03/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

class ProfileConfigurator {
    
    // MARK: - Object lifecycle

    static let instance = ProfileConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: ProfileViewController) {
        
        let router = ProfileRouter(viewController: viewController)
        let presenter = ProfilePresenter(output: viewController)
        let interactor = ProfileInteractor(output: presenter)
        
        viewController.output = interactor
        viewController.router = router
    }
}
