//
//  ChangePassPresenter.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/22/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol ChangePassPresenterInput {
    
    func beginChange()
    func didChanged()
    func gotError(_ error: Error)
    func handleInput(_ isValid: Bool)
}

protocol ChangePassPresenterOutput: class {
    
    func didChanged()
    func showError(_ error: String)
    func toggleButton(_ isEnabled: Bool)
    func toggleView(_ isEnabled: Bool)
}

class ChangePassPresenter: ChangePassPresenterInput {
    
    private weak var output: ChangePassPresenterOutput?

    init(output: ChangePassPresenterOutput) {
        self.output = output
    }

    // MARK: - Presentation logic

    func beginChange() {
        output?.toggleButton(false)
        output?.toggleView(false)
    }
    
    func didChanged() {
        output?.toggleButton(true)
        output?.toggleView(true)
        output?.didChanged()
    }
    
    func gotError(_ error: Error) {
        output?.toggleButton(true)
        output?.toggleView(true)
        output?.showError(String(describing: error))
    }
    
    func handleInput(_ isValid: Bool) {
        output?.toggleButton(isValid)
    }
}
