//
//  ChangePassInteractor.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/22/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol ChangePassInteractorInput {
    
    func checkInput(_ input: ChangePass.Input)
    func change(with input: ChangePass.Input)
}

class ChangePassInteractor: ChangePassInteractorInput, ChangePassWorkerOutput {
    
    private let output: ChangePassPresenterInput
    private let worker: ChangePassWorker

    init(output: ChangePassPresenterInput) {
        
        self.output = output
        
        worker = ChangePassWorker()
        worker.output = self
    }

    // MARK: - Business logic

    func checkInput(_ input: ChangePass.Input) {
        output.handleInput(input.isValid)
    }
    
    func change(with input: ChangePass.Input) {
        output.beginChange()
        worker.change(with: input)
    }

    // MARK: - Worker Output

    func didChanged(with output: ChangePass.Output) {
        self.output.didChanged()
    }
    
    func gotError(_ error: Error) {
        output.gotError(error)
    }
}
