//
//  ChangePassModels.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/22/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

struct ChangePass {
    
    struct Input {
        
        let oldPassword: String?
        let newPassword: String?
        let confirmPassword: String?
    }

    struct Output {
    }

    struct ViewModel {
    }
}

extension ChangePass.Input {
    
    var isValid: Bool {
        guard let oldPassword = oldPassword else { return false }
        guard let newPassword = newPassword else { return false }
        guard let confirmPassword = confirmPassword else { return false }
        
        return oldPassword.length >= minPasswordLength && newPassword.length >= minPasswordLength && newPassword == confirmPassword
    }
}
