//
//  ChangePassWorker.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/22/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol ChangePassWorkerInput {
    func change(with input: ChangePass.Input)
}

protocol ChangePassWorkerOutput: class {
    func didChanged(with output: ChangePass.Output)
    func gotError(_ error: Error)
}

class ChangePassWorker: ChangePassWorkerInput
{
    weak var output: ChangePassWorkerOutput?

    // MARK: - Business Logic

    func change(with input: ChangePass.Input) {
        
        let params = ChangePasswordParams()
        params.newPassword = input.newPassword
        params.oldPassword = input.oldPassword
        
        ChangePassword(params: params).exec { result in
            switch result {
            case .value(_):
                self.output?.didChanged(with: ChangePass.Output())
            case .error(let error):
                self.output?.gotError(error)
            }
        }
    }
}
