//
//  ChangePassConfigurator.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/22/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

class ChangePassConfigurator {
    
    // MARK: - Object lifecycle

    static let instance = ChangePassConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: ChangePassViewController) {
        
        let router = ChangePassRouter(viewController: viewController)
        let presenter = ChangePassPresenter(output: viewController)
        let interactor = ChangePassInteractor(output: presenter)
        
        viewController.output = interactor
        viewController.router = router
    }
}
