//
//  EditProfileRouter.swift
//  Mabius
//
//  Created by Timafei Harhun on 3/01/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol EditProfileRouterInput {
    func changeMail()
    func changePass()
    func logout()
}

class EditProfileRouter: EditProfileRouterInput {
    
    weak var viewController: EditProfileViewController!

    init(viewController: EditProfileViewController) {
        self.viewController = viewController
    }

    // MARK: - Navigation

    func changeMail() {
        UIApplication.openUrl("cyl://ChangeMailViewController")
    }
    
    func changePass() {
        UIApplication.openUrl("cyl://ChangePassViewController")
    }
    
    func logout() {
        UIApplication.openUrl("cyl://logout")
    }
}
