//
//  Step1Presenter.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/24/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol Step1PresenterInput {
    func handleInput(_ isValid: Bool)
}

protocol Step1PresenterOutput: class {
    func toggleNextButton(_ isEnabled: Bool)
}

class Step1Presenter: Step1PresenterInput {
    
    private weak var output: Step1PresenterOutput?

    init(output: Step1PresenterOutput) {
        self.output = output
    }

    // MARK: - Presentation logic
    
    func handleInput(_ isValid: Bool) {
        output?.toggleNextButton(isValid)
    }
}
