//
//  Step1Interactor.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/24/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//


protocol Step1InteractorInput {
    func checkInput(_ input: Step1.Input)
}

class Step1Interactor: Step1InteractorInput {
    
    private let output: Step1PresenterInput

    init(output: Step1PresenterInput) {
        self.output = output
    }

    // MARK: - Business logic
    
    func checkInput(_ input: Step1.Input) {
        output.handleInput(input.isValid)
    }
}
