//
//  Step1Models.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/24/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

enum ProjectKind: String {
    case mabius = "mabius"
    case enactus = "enactus"
    
    static func getProjectKind(by project: String) -> ProjectKind {
        switch project {
        case "mabius":
            return self.mabius
        case "enactus":
            return self.enactus
        default:
            return self.mabius
        }
    }
}

enum ProjectType: String {
    case idea = "enactus_idea"
    case event = "enactus_event"
    case project = "mabius_idea"
    
    static func getProjectType(by type: String) -> ProjectType {
        switch type {
        case "enactus_idea":
            return self.idea
        case "enactus_event":
            return self.event
        case "mabius_idea":
            return self.project
        default:
            return self.idea
        }
    }
}

struct Step1 {
    
    struct Input {
        var selectedProject: ProjectKind?
        var selectedType: ProjectType?
    }

    struct Output {
    }

    struct ViewModel {
    }
}

extension Step1.Input {
    var isValid: Bool {
        guard let project = selectedProject else { return false }
        if project == .mabius { return true }
        guard project == .enactus, let _ = selectedType else { return false }
        return true
    }
}
