//
//  InviteConfigurator.swift
//  Mabius
//
//  Created by Timafei Harhun on 15.02.17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

class InviteConfigurator
{
    // MARK: - Object lifecycle

    static let instance = InviteConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: InviteViewController)
    {
        let router = InviteRouter(viewController: viewController)
        let presenter = InvitePresenter(output: viewController)
        let interactor = InviteInteractor(output: presenter)
        
        viewController.output = interactor
        viewController.router = router
    }
}
