//
//  InviteWorker.swift
//  Mabius
//
//  Created by Timafei Harhun on 15.02.17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol InviteWorkerInput
{
    func invite(with input: Invite.Input.Data)
}

protocol InviteWorkerOutput: class
{
    func didInvited(with output: Invite.Output)
    func gotError(_ error: Error)
}

class InviteWorker: InviteWorkerInput
{
    weak var output: InviteWorkerOutput?

    // MARK: - Business Logic

    func invite(with input: Invite.Input.Data)
    {
        let params = InviteParams()
        params.email = input.email
        params.about = input.note
        
        AskInvite(params: params).exec { result in
            switch result {
            case .value(_):
                self.output?.didInvited(with: Invite.Output())
            case .error(let error):
                self.output?.gotError(error)
            }
        }
    }
}
