//
//  InviteRouter.swift
//  Mabius
//
//  Created by Timafei Harhun on 15.02.17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import SafariServices

protocol InviteRouterInput
{
    func proceedSuccess()
    func openTerms()
    func openAgreement()
}

class InviteRouter: InviteRouterInput
{
    weak var viewController: InviteViewController!

    init(viewController: InviteViewController)
    {
        self.viewController = viewController
    }

    // MARK: - Navigation
    
    func proceedSuccess() {
        UIApplication.openUrl("cyl://InfoViewController?type=2")
    }
    
    func openTerms() {
        let urlString = "http://files.meallions.show/user_agreement_application_meallions.pdf"
        
        if let url = URL(string: urlString) {
            let svc = SFSafariViewController(url: url, entersReaderIfAvailable: true)
            viewController.present(svc, animated: true)
        }
    }
    
    func openAgreement() {
        let urlString = "http://files.meallions.show/agreement_on_the_conditions_for_filing_an_application_in_the_annex_meallions.pdf"
        
        if let url = URL(string: urlString) {
            let svc = SFSafariViewController(url: url, entersReaderIfAvailable: true)
            viewController.present(svc, animated: true)
        }
    }
}
