//
//  InviteModelsModels.swift
//  Mabius
//
//  Created by Timafei Harhun on 15.02.17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

struct Invite
{
    struct Input
    {
        struct Data
        {
            var email: String?
            var note: String?
        }
    }

    struct Output
    {
    }

    struct ViewModel
    {
    }
}

extension Invite.Input.Data
{
    var isValid: Bool {
        guard let mail = email else { return false }
        guard let note = note else { return false }
        return mail.isEmail && note.length >= minCommentLength
    }
}

let minCommentLength = 1
