//
//  WhoConfigurator.swift
//  Mabius
//
//  Created by Timafei Harhun on 06/03/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

class WhoConfigurator {
    
    // MARK: - Object lifecycle

    static let instance = WhoConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: WhoViewController) {
        
        let router = WhoRouter(viewController: viewController)
        let presenter = WhoPresenter(output: viewController)
        let interactor = WhoInteractor(output: presenter)
        
        viewController.output = interactor
        viewController.router = router
    }
}
