//
//  WhoInteractor.swift
//  Mabius
//
//  Created by Timafei Harhun on 06/03/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol WhoInteractorInput {
    
    func loadLikes(with input: Who.Input)
}

class WhoInteractor: WhoInteractorInput, WhoWorkerOutput {
    
    private let output: WhoPresenterInput
    private let worker: WhoWorker

    init(output: WhoPresenterInput) {
        self.output = output
        worker = WhoWorker()
        worker.output = self
    }

    // MARK: - Business logic

    func loadLikes(with input: Who.Input) {
        output.beganLoadLikes()
        worker.loadLikes(with: input)
    }
    
    // MARK: - Worker Output
    
    func didLoadLikes(_ likes: [Like]) {
        output.didLoadLikes(likes)
    }
    
    func gotError(_ error: Error) {
        output.gotError(error)
    }
}
