//
//  WhoModels.swift
//  Mabius
//
//  Created by Timafei Harhun on 06/03/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

struct Who {
    
    struct Input {
        var pointId: Int
    }

    struct Output {}

    struct ViewModel {
        var likes = [Like]()
    }
}
