//
//  WhoPresenter.swift
//  Mabius
//
//  Created by Timafei Harhun on 06/03/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol WhoPresenterInput {
    
    func beganLoadLikes()
    func didLoadLikes(_ likes: [Like])
    func gotError(_ error: Error)
}

protocol WhoPresenterOutput: class {
    
    func didLoadLikes(_ likes: [Like])
    func showError(_ error: String)
    func toggleView(_ isEnabled: Bool)
}

class WhoPresenter: WhoPresenterInput {
    
    private weak var output: WhoPresenterOutput?

    init(output: WhoPresenterOutput) {
        self.output = output
    }

    // MARK: - Presentation logic

    func beganLoadLikes() {
        output?.toggleView(false)
    }
    
    func endLoading() {
        output?.toggleView(true)
    }
    
    func didLoadLikes(_ likes: [Like]) {
        output?.toggleView(true)
        output?.didLoadLikes(likes)
    }

    func gotError(_ error: Error) {
        output?.toggleView(true)
        output?.showError(String(describing: error))
    }

}
