//
//  WhoRouter.swift
//  Mabius
//
//  Created by Timafei Harhun on 06/03/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol WhoRouterInput {
    func showUserInfo(_ userId: Int)
}

class WhoRouter: WhoRouterInput {
    
    weak var viewController: WhoViewController!

    init(viewController: WhoViewController) {
        self.viewController = viewController
    }

    // MARK: - Navigation

    func showUserInfo(_ userId: Int) {
        UIApplication.openUrl("cyl://ProfileViewController?userId=\(userId)&selfProfile=false")
    }
}
