//
//  Step2Configurator.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/24/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

class Step2Configurator {
    
    // MARK: - Object lifecycle

    static let instance = Step2Configurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: Step2ViewController) {
        let router = Step2Router(viewController: viewController)
        let presenter = Step2Presenter(output: viewController)
        let interactor = Step2Interactor(output: presenter)
        
        viewController.output = interactor
        viewController.router = router
    }
}
