//
//  Step2Worker.swift
//  Mabius
//
//  Created by Timafei Harhun on 3/14/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol Step2WorkerInput {
    func uploadImage(_ image: UIImage)
}

protocol Step2WorkerOutput: class {
    func didUploadImage(_ response: Step2.Output)
    func gotError(_ error: Error)
}

class Step2Worker: Step2WorkerInput {
    
    weak var output: Step2WorkerOutput?

    // MARK: - Business Logic

    func uploadImage(_ image: UIImage) {
        UploadImage(image: image).exec { result in
            switch result {
            case .value(let response):
                self.output?.didUploadImage(Step2.Output(imageId: response.object.id))
            case .error(let error):
                self.output?.gotError(error)
            }
        }
    }
}
