//
//  Step2Router.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/24/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol Step2RouterInput {
    func proceedNext()
    func showMap()
    func showImagePicker()
}

protocol Step2RouterOutput {
    func setAddress(address: String, with location: Location)
}

class Step2Router: Step2RouterInput {
   
    weak var viewController: Step2ViewController!

    init(viewController: Step2ViewController) {
        self.viewController = viewController
    }

    // MARK: - Navigation

    func proceedNext() {
        let vc = viewController.storyboard?.instantiateViewController(withIdentifier: "Step3ViewController") as! Step3ViewController
        vc.point = viewController.point
        vc.transfer = Step3.Transfer(step1:viewController.transfer?.step1, step2:viewController.input)
        viewController.navigationController?.pushViewController(vc, animated: true)
    }
    
    func showMap() {
        let vc = viewController.storyboard?.instantiateViewController(withIdentifier: "PlaceViewController") as! PlaceViewController
        
        if let country = viewController.model.address.country, let city = viewController.model.address.city, let address = viewController.model.address.address {
            vc.address = Place.ViewModel(country: country, city: city, address: address, more: viewController.model.address.more)
        }
        
        vc.didSetAddress = { [weak self] fullAddress, country, city, address, more, location in
            self?.viewController.setAddress(address: fullAddress, with: location)
            self?.viewController.model.address = Step2.Address(country: country, city: city, address: address, more: more)
        }
        
        viewController.present(vc, animated: true, completion: nil)
    }
    
    func showImagePicker() {
        viewController.present(viewController.imagePicker, animated: true, completion: nil)
    }
    
    func proceedBack() {
        _ = viewController.navigationController?.popViewController(animated: true)
    }
    
    func proceedFeed() {
        viewController.tabBarController?.selectedIndex = 0
    }
}
