//
//  Step2Presenter.swift
//  Mabius
//
//  Created by Timafei Harhun on 2/24/17.
//  Copyright (c) 2017 vice3.agency. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

protocol Step2PresenterInput {
    func handleInput(_ isValid: Bool)
    func beginLoad()
    func didUploadImage(_ response: Step2.Output)
    func gotError(_ error: Error)
}

protocol Step2PresenterOutput: class {
    func toggleNextButton(_ isEnabled: Bool)
    func didUploadImage(_ response: Step2.Output)
    func showError(_ error: String)
    func toggleView(_ isEnabled: Bool)
}

class Step2Presenter: Step2PresenterInput {
    private weak var output: Step2PresenterOutput?

    init(output: Step2PresenterOutput) {
        self.output = output
    }

    // MARK: - Presentation logic
    
    func beginLoad() {
        beginActivity()
    }
    
    func handleInput(_ isValid: Bool) {
        output?.toggleNextButton(isValid)
    }
    
    func didUploadImage(_ response: Step2.Output) {
        endActivity()
        output?.didUploadImage(response)
    }
    
    func gotError(_ error: Error) {
        endActivity()
        output?.showError(String(describing: error))
    }
    
    // MARK: - Activity
    
    fileprivate func beginActivity() {
        output?.toggleView(false)
    }
    
    fileprivate func endActivity() {
        output?.toggleView(true)
    }
}
